### ISSUE TITLE
[feat] create Slot Component

### ISSUE THREAD

**Issue by dmdgpdi** [Kernel360/FE1_E2E_sumtime#14]
## Feature Name
slot 컴포넌트에서 값을 받아서 렌더링을 구현한다.
slot 컴포넌트의 props는 아래와 같다.
- headerDate
- slotTime
- taskitem?

해당 props를 이용해서 TimeSlot, TaskSlot 컴포넌트 만들기

<hr>

아래의 PR에서 달아주신 코멘트처럼 아직 해결되지 않은 문제가 존재합니다. https://github.com/Kernel360/FE1_E2E_sumtime/pull/19#pullrequestreview-2209194382
(#19 의 screenshot을 보면 더 명확해집니다.)
1. 공통된 taskItem에서 중복되서 보이는 taskItem의 title, subTitle 문제 
2. title, subTitle이 색칠된 영역을 벗어나는 문제

해당 문제를 해결하기 위한 기능을 추가해야합니다.

## Progress

- [x] TimeSlot 컴포넌트 만들기
- [x] TaskSlot 컴포넌트 만들기
- [ ] Slot에 적절하게 값을 전달하기.(중복 출력 방지)
- [ ] Slot에서 색칠된 영역 내에 title, subTitle 출력

**Comment by Yejin0O0** [comment]
issue title이 이상합니다~!~
