### ISSUE TITLE
[fix] fix CurrentTimeLine in vercel

### ISSUE THREAD

**Issue by dmdgpdi** [Kernel360/FE1_E2E_sumtime#80]
**Describe the bug**
로컬에서는 문제가 없으나 배포시에 CurrentTimeLine이 현재 시간을 가리키지 않습니다.

**To Reproduce**
1. 배포된 사이트에 접속한다. `배포된주소/timetable`
**Expected behavior**

**Screenshots**
### 버그 발견 시간
<img width="174" alt="스크린샷 2024-08-07 오후 6 45 23" src="https://github.com/user-attachments/assets/41964858-9859-461c-a0c7-1b9aaeb3fe67">
### 배포시에 CurrentTimeLine
<img width="311" alt="스크린샷 2024-08-07 오후 6 45 06" src="https://github.com/user-attachments/assets/837896fa-52d9-449d-8db1-7e0809d9b9c7">
### 로컬의 CurrentTimeLine
<img width="175" alt="스크린샷 2024-08-07 오후 6 45 46" src="https://github.com/user-attachments/assets/6a9000b2-1135-4b1d-9b53-0c6196d325bf">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Yejin0O0** [comment]
https://vercel.com/docs/functions/configuring-functions/region

vercel 지역 관련 설정 문서 첨부합니다! 도움이 되었으면 좋겠습니다!!

**Comment by haejinyun** [comment]
https://sooros.com/SSG%EC%97%90%EC%84%9C-%EC%8B%9C%EA%B0%84-%EA%B4%80%EB%A0%A8-%ED%8A%B8%EB%9F%AC%EB%B8%94%EC%8A%88%ED%8C%85
SSR관련 문서 첨부합니다..!

**Comment by dmdgpdi** [comment]
해당 버그는 #89 PR에서 로직을 변경된 뒤에 해결됐습니다.
